repos:
  - repo: https://github.com/semgrep/pre-commit
    rev: v1.130.0
    hooks:
      - id: semgrep
        args:
          - --config=p/security-audit
          - --config=p/python
          - --error